# Generated by Django 5.2.17 on 2026-10-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailotp'),
        ('accounts', '0004_pendingregistration'),
    ]

    operations = [
    ]
