
"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django.
"""

from pathlib import Path
import os


BASE_DIR = Path(__file__).resolve().parent.parent


# ----------------------------------------------------
# Read secret values (email password, Google keys...) from a
# file called ".env" in the project folder, so they are never
# written inside the code. Each line looks like:  NAME=value
# ----------------------------------------------------
def load_env_file():
    env_path = BASE_DIR / '.env'
    if not env_path.exists():
        return

    for line in env_path.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        name, value = line.split('=', 1)
        value = value.strip().strip('"').strip("'")
        # A value already set in the system wins over the .env file.
        os.environ.setdefault(name.strip(), value)


load_env_file()


SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-local-development-key-change-me'
)

DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [host.strip() for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',') if host.strip()]


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'products',
    'cart',
    'orders',
    'payments',
    'dashboard',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]




ROOT_URLCONF = 'ecommerce.urls'




TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'



MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'



# ----------------------------------------------------
# Email (used to send the OTP code)
# If EMAIL_HOST_USER and EMAIL_HOST_PASSWORD are set in the .env file,
# real emails are sent through Gmail. If they are empty, the email is
# only PRINTED in the terminal - handy while testing.
# ----------------------------------------------------
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
# Gmail shows app passwords with spaces; we remove them to be safe.
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '').replace(' ', '')

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_TIMEOUT = 15
    DEFAULT_FROM_EMAIL = f'E-Commerce Shop <{EMAIL_HOST_USER}>'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'E-Commerce Shop <noreply@ecommerce.local>'

# OTP rules
OTP_EXPIRY_MINUTES = 10     # how long a code stays valid
OTP_RESEND_SECONDS = 30     # wait time before a new code can be requested
OTP_MAX_ATTEMPTS = 5        # wrong tries allowed per code

# ----------------------------------------------------
# "Continue with Google" (get these from Google Cloud Console)
# ----------------------------------------------------
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')



LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# Real payment credentials are intentionally not stored in source code.
# The current checkout uses a clearly labelled demo payment flow.
RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET', '')

if not DEBUG:
    if SECRET_KEY == 'django-insecure-local-development-key-change-me':
        raise RuntimeError('Set DJANGO_SECRET_KEY when DJANGO_DEBUG=False.')
    if not ALLOWED_HOSTS:
        raise RuntimeError('Set DJANGO_ALLOWED_HOSTS when DJANGO_DEBUG=False.')





DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
